version = 1

[merge]
automerge_label = "automerge"

[merge.automerge_dependencies]
# auto merge all PRs opened by "renovate" that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
versions = ["minor", "patch"]
usernames = ["renovate"]

[approve]
auto_approve_usernames = ["renovate"]
