name: release

on:
  push:
    # run only against tags prefixed with v
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PUSH }} # use a custom PAT of a user with allows branch-protection bypass
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure git
        run: |
          git config --global user.name 'openfeature-ci'
          git config --global user.email 'openfeature-ci@users.noreply.github.com'

      - name: Version
        run: npm version ${{ env.GITHUB_REF_NAME }}

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Version Update
        run: git push
